smoke_weed:
  url: "https://youtu.be/U1ei5rwO7ZI"
  from: 0
  to: -1
lemon_tree:
  url: "https://www.youtube.com/watch?v=sJQYoGyEtDs"
  from: 0
  to: -1

someday:
  url: "https://www.youtube.com/watch?v=e5QEAI_O2IA"
  from: 0
  to: -1
